apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: acs-operator
  annotations:
    description: Template to deploy the ACS operator on OCP.
    tags: acs,management,operator
    iconClass: icon-openshift
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:

- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${ACS_OPERATOR_NAMESPACE}
    annotations:
      openshift.io/description: "This project contains all the resources related to the ACS operator"
      openshift.io/display-name: "ACS Operator"

- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: rhacs-operator
    namespace: ${ACS_OPERATOR_NAMESPACE}
  spec: {}

- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: rhacs-operator
    namespace: ${ACS_OPERATOR_NAMESPACE}
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: rhacs-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace

parameters:
- name: ACS_OPERATOR_NAMESPACE
  description: "The project where ACS and its operator will be installed."
  required: false
  value: "rhacs-operator"
